name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . -f build.dockerfile -t aktharmiah/spring-demo-payroll:latest
      
    - name : Login to docker
      run: docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)
      
    - name : Push newly created image to Docker hub
      run: docker push aktharmiah/spring-demo-payroll:latest
